# Generated by Django 4.2.7 on 2023-11-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='datetime',
            field=models.CharField(max_length=200),
        ),
    ]
