# Generated by Django 4.2.7 on 2023-11-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticketinfo_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
