# Generated by Django 4.2.7 on 2023-11-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketinfo_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketinfo',
            name='datetime',
        ),
        migrations.AddField(
            model_name='ticketinfo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
