# Generated by Django 4.2.7 on 2023-11-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticketinfo_datetime_ticketinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinfo',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
